### ISSUE TITLE
Uncaught error: replica.ipkg:41:3--43:1:Replica.Version not found

### ISSUE THREAD

**Issue by teto** [ReplicaTest/REPLica#58]
I've tried to update to 9e36c85 to solve an issue of mine but when building via the flake I got `Uncaught error: replica.ipkg:41:3--43:1:Replica.Version not found`. Seems like an idriss error but the CI passes so not sure what s wrong xD

**Comment by berewt** [comment]
oh, it's probably because the `Replica.Version` file is generated thanks to `make`.
Not sure how it can be solved though...

**Comment by berewt** [comment]
I really need to level up on `nix`, and probably to add a pipeline for it in the CI.

**Comment by teto** [comment]
nix's learning curve is steep but the payoff absolutely worth it if you do software professionnaly. Once `nix flakes` make it to the stable branch, the trickiest part of nix will have been solved.

The generic code to build idriss packages is here https://github.com/teto/nixpkgs/blob/nixos-unstable/pkgs/development/idris-modules/build-idris-package.nix 

Now that I've seen https://github.com/ReplicaTest/REPLica/blob/308b02f7f41368adf012679a303d34ab001a9cb4/Makefile#L10 I can probably fix the package (maybe next week rather).

**Comment by berewt** [comment]
I asked the idris forum for help too, we need either to replace `idris --build` in the build phase by `make build` or, probably better, to launch `make src/Replica/Version.idr` before the build.

**Comment by berewt** [comment]
`main` should work for you now. I've upgraded to the recent Idris 0.5.1 release, I guess the new flake should probably stick to it.

**Comment by berewt** [comment]
Close by #66

**Comment by teto** [comment]
thanks for working on this. Very happy to be able to use replica again.
