### ISSUE TITLE
interactive runs asks me if I want to replace the golden value even though they are identical

### ISSUE THREAD

**Issue by teto** [ReplicaTest/REPLica#60]
I am now polishing my golden tests and so ran a sequence of interactive mode.
For each test I get
```
Do you want to replace the golden value? [N/y]
```
even though I haven't changed anything to my program, Outputs are similar. Replica should detect it and skip the question ?

NB: is there an option to show a diff of "expected vs actual result" ?

**Comment by berewt** [comment]
It should catch it, and it should display the golden value and the given output by default. Here is an example of a mismatch on an output:

```
   replica run -i hello.json
--------------------------------------------------------------------------------
Running tests...
hello: Golden value mismatch for standard output
Expected:
Hello, World!

Given:
Hello, Wrld!

Do you want to replace the golden value? [N/y]
```

I thought first that replica might not be able to read the golden value, but it isn't the case, as in this case it would ask you to **set** the output, not to replace it.

**Comment by berewt** [comment]
Was this one solved or should we keep it open, I wasn't able to replicate the issue on my side (yet).

**Comment by teto** [comment]
Will close and reopen if this arises again.
